UISEEDSIGNER_MOD_DIR := $(USERMOD_DIR)
UISEEDSIGNER_BUILD_DIR := $(UISEEDSIGNER_MOD_DIR)/../../build-115

SRC_USERMOD_C += $(UISEEDSIGNER_MOD_DIR)/mod_uiseedsigner.c
CFLAGS_USERMOD += -I$(UISEEDSIGNER_MOD_DIR) -I$(UISEEDSIGNER_MOD_DIR)/../../include -I$(UISEEDSIGNER_MOD_DIR)/../../config
LDFLAGS_USERMOD += -L$(UISEEDSIGNER_BUILD_DIR) -L$(UISEEDSIGNER_BUILD_DIR)/lib -lseedsigner_lvgl -llvgl -lstdc++
